export const GET_COUNTRY_LIST = {
  REQUEST: 'GET_CONTRY_LIST_REQUEST',
  SUCCESS: 'GET_CONTRY_LIST_SUCCESS',
  FAILURE: 'GET_CONTRY_LIST_FAILURE',
  REFRESH: 'GET_CONTRY_LIST_REFRESH',
};

export const SORT_TOTAL_CONFIRMED = {
  REQUEST: 'SORT_TOTAL_CONFIRMED_REQUEST',
};
export const SORT_HIGHEST_DEATHS = {
  REQUEST: 'SORT_HIGHEST_DEATHS_REQUEST',
};
export const SORT_LEAST_RECOVERED = {
  REQUEST: 'SORT_LEAST_RECOVERED_REQUEST',
};

export const LOADING_TABLE = {
  SHOW: 'LOADING_TABLE_SHOW',
  HIDEN: 'LOADING_TABLE_HIDEN',
};
export const GET_DETAIL_COUNTRY = {
  REQUEST: 'GET_DETAIL_COUNTRY_REQUEST',
  SUCCESS: 'GET_DETAIL_COUNTRY_SUCCESS',
  FAILURE: 'GET_DETAIL_COUNTRY_FAILURE',
  REFRESH: 'GET_DETAIL_COUNTRY_REFRESH',
};
export const LOADING_FULLSCREEN = {
  SHOW: 'LOADING_FULLSCREEN_SHOW',
  HIDEN: 'LOADING_FULLSCREEN_HIDEN',
};
export const GET_TV_LIST = {
  REQUEST: 'GET_TV_LIST_REQUEST',
  SUCCESS: 'GET_TV_LIST_SUCCESS',
  FAILURE: 'GET_TV_LIST_FAILURE',
  REFRESH: 'GET_TV_LIST_REFRESH',
};

export const GET_VIDEOS = {
  REQUEST: 'GET_VIDEOS_REQUEST',
  SUCCESS: 'GET_VIDEOS_SUCCESS',
  FAILURE: 'GET_VIDEOS_FAILURE',
  REFRESH: 'GET_VIDEOS_REFRESH',
};

export const GET_DETAIL_MOVIE = {
  REQUEST: 'GET_DETAIL_MOVIE_REQUEST',
  SUCCESS: 'GET_DETAIL_MOVIE_SUCCESS',
  FAILURE: 'GET_DETAIL_MOVIE_FAILURE',
  REFRESH: 'GET_DETAIL_MOVIE_REFRESH',
};

export const GET_CREDITS_LIST = {
  REQUEST: 'GET_CREDITS_LIST_REQUEST',
  SUCCESS: 'GET_CREDITS_LIST_SUCCESS',
  FAILURE: 'GET_CREDITS_LIST_FAILURE',
  REFRESH: 'GET_CREDITS_LIST_REFRESH',
};
export const SEARCH_DETAIL_MOVIE = {
  REQUEST: 'SEARCH_DETAIL_MOVIE_REQUEST',
  SUCCESS: 'SEARCH_DETAIL_MOVIE_SUCCESS',
  FAILURE: 'SEARCH_DETAIL_MOVIE_FAILURE',
  REFRESH: 'SEARCH_DETAIL_MOVIE_REFRESH',
};
export const GET_SIMILAR_LIST = {
  REQUEST: 'GET_SIMILAR_LIST_REQUEST',
  SUCCESS: 'GET_SIMILAR_LIST_SUCCESS',
  FAILURE: 'GET_SIMILAR_LIST_FAILURE',
  REFRESH: 'GET_SIMILAR_LIST_REFRESH',
};
